---
title: "440minicase1_rmd"
output: html_document
date: "2024-09-05"
---

```{r}
library(readxl)
library(dplyr)
```

```{r}
survey <- read_excel("Durham_2022_Resident_Survey_Raw_Data (1).xlsx")
```

```{r}
#RESPONSE: Perceived resident ratings of Durham as a place to live (Q24)
  #Q24 has 10 parts, each a rating of 1-5, with 9 meaning N/A
    #thus we shall create a variable which is simply a total of this; if value of 9, change to zero; sum all values

#EXPLORE ASSOCIATION WITH: length of time residents have lived in Durham (Q27)

#ADJUST FOR:
              #resident's total annual household income (Q33)
                #this variable is ordinal
              #whether monthly housing costs (rent or mortgage) exceed 30% of the resident's monthly income (Q9.1)
                #this variable is binary (theoretically, but it includes a third value for N/A)
              #other variables (existing or derived)
```

```{r}
survey$`Q24[01] [01  As a place to live]`[survey$`Q24[01] [01  As a place to live]` == 9] <- 0
survey$`Q24[02] [02  As a place to work]`[survey$`Q24[02] [02  As a place to work]` == 9] <- 0
survey$`Q24[03] [03  As a place to play]`[survey$`Q24[03] [03  As a place to play]` == 9] <-0
survey$`Q24[04] [04  As a place to raise childre`[survey$`Q24[04] [04  As a place to raise childre` == 9] <- 0
survey$`Q24[05] [05  As a place to educate child`[survey$`Q24[05] [05  As a place to educate child` == 9] <- 0
survey$`Q24[06] [06  As a place to retire]`[survey$`Q24[06] [06  As a place to retire]` == 9] <- 0
survey$`Q24[07] [07  As a place to visit]`[survey$`Q24[07] [07  As a place to visit]` == 9] <- 0
survey$`Q24[08] [08  As a place to start a busin`[survey$`Q24[08] [08  As a place to start a busin` == 9] <- 0
survey$`Q24[09] [09  As a community that is movi`[survey$`Q24[09] [09  As a community that is movi` == 9] <- 0
survey$`Q24[10] [10  As a community that values`[survey$`Q24[10] [10  As a community that values` == 9] <- 0

#create rating variable which is total of all 10 parts of Q24
#ASSUMPTION: the N/A values are independent of rating (i.e. observations of people who would rate Durham as a bad place to live are equally as likely to contain N/A values as observations of people who would rate Durham as a good place to live)
survey <- survey %>%
  mutate(rating = `Q24[01] [01  As a place to live]` +
           `Q24[02] [02  As a place to work]` +
           `Q24[03] [03  As a place to play]` +
           `Q24[04] [04  As a place to raise childre` +
           `Q24[05] [05  As a place to educate child` +
           `Q24[06] [06  As a place to retire]` +
           `Q24[07] [07  As a place to visit]` +
           `Q24[08] [08  As a place to start a busin` +
           `Q24[09] [09  As a community that is movi` +
           `Q24[10] [10  As a community that values`)
```

```{r}
length(survey$`Q33  Would you say your total annual hou`[survey$`Q33  Would you say your total annual hou` == 9])
length(survey$`Q9[01]  [1  Do your monthly housing cost`[survey$`Q9[01]  [1  Do your monthly housing cost` == 9])
```

```{r}
#I want to include missing values for both Q33 and Q9.1 because there are a significant number of missing values for them both
#However, I do not want to fit the model using observations with missing data for time spent in Durham. The reason for this is because later I want to compare nested models, and to do so, the models must be fit to the same data
#Q33 is an ordinal variable, but a "Missing" category would not fit into the ranking structure, so I will simply treat Q33 as a non-ordinal categorical variable
survey_clean <- survey[complete.cases(survey[, 208]), ]
basemod <- lm(rating ~ as.factor(`Q33  Would you say your total annual hou`) + as.factor(`Q9[01]  [1  Do your monthly housing cost`), data = survey_clean)
summary(basemod)
```

```{r}
#EDA for other potential predictors
##I am curious if individuals of different racial backgrounds have a different perception of Durham
survey_clean %>%
  filter(`Q32[01]  [Asian or Asian Indian]` == 1) %>%
  summarize(avg_rating = mean(rating))
survey_clean %>%
  filter(`Q32[02]  [Black or African American]` == 2) %>%
  summarize(avg_rating = mean(rating))
survey_clean %>%
  filter(`Q32[03]  [American Indian or Alaska Nati` == 3) %>%
  summarize(avg_rating = mean(rating))
survey_clean %>%
  filter(`Q32[04]  [White]` == 4) %>%
  summarize(avg_rating = mean(rating))
survey_clean %>%
  filter(`Q32[05]  [Native Hawaiian or other Pacif` == 5) %>%
  summarize(avg_rating = mean(rating))
survey_clean %>%
  filter(`Q32[06]  [Other]` == 6) %>%
  summarize(avg_rating = mean(rating))
```

```{r}
#EDA for other potential predictors (cont.)
##I am curious if gender plays a role in predicting perception of Durham
survey_clean %>%
  filter(`Q29  What is your gender?` == 1) %>%
  summarize(avg_rating = mean(rating))
survey_clean %>%
  filter(`Q29  What is your gender?` == 2) %>%
  summarize(avg_rating = mean(rating))
survey_clean %>%
  filter(`Q29  What is your gender?` == 3) %>%
  summarize(avg_rating = mean(rating))
survey_clean %>%
  filter(`Q29  What is your gender?` == 4) %>%
  summarize(avg_rating = mean(rating))
```

```{r}
#the ratings seem to be roughly the same across races (except for Native Hawaiian / Pacific Islander, but there is only one data point for that), so we will not include race as a predictor
```

```{r}
#full model with time lived in Durham as predictor
fullmod <- lm(rating ~ as.factor(`Q33  Would you say your total annual hou`) + as.factor(`Q9[01]  [1  Do your monthly housing cost`) + `Q27  Approximately how many years have y`, data = survey_clean)
summary(fullmod)
```

```{r}
#LRT
library(lmtest)
lrtest(basemod, fullmod)
```

```{r}
#F-test
anova(basemod, fullmod)
```

```{r}
#Both the LRT and F-test suggest that length of time lived in Durham is a significant predictor of rating
```

```{r}
fullmod_gender <- lm(rating ~ as.factor(`Q33  Would you say your total annual hou`) + as.factor(`Q9[01]  [1  Do your monthly housing cost`) + `Q27  Approximately how many years have y` + as.factor(`Q29  What is your gender?`), data = survey_clean)
summary(fullmod_gender)
```

```{r}
#LRT (gender)
lrtest(fullmod, fullmod_gender)
```

```{r}
#F-test (gender)
anova(fullmod, fullmod_gender)
```

```{r}
#AIC & BIC
AIC(fullmod)
AIC(fullmod_gender)
BIC(fullmod)
BIC(fullmod_gender)
```

```{r}
#We see that BIC is higher for the model with gender because BIC penalizes for the extra predictor, and the predictor itself doesn't add much predictive value
```

